config/routes.rb
Rails.application.routes.draw do
  resources :portfolios
  resources :images
  resources :worlds
  resources :world_notes
  resources :story_locations
  resources :story_characters
  resources :locations
  resources :characters
  resources :story_notes
  resources :stories
  resources :names
  resources :users, only: [:create]
  resources :auth

  post '/login', to: 'auth#login'
  post '/signup', to: 'users#create'

  post '/getworlds', to: 'worlds#getworlds'
  post '/getworld', to: 'worlds#getworld'
  post '/getworld_note', to: 'world_notes#getworld_note'
  post '/getworld_notes', to: 'world_notes#getworld_notes'
  post '/getworldstories', to: 'stories#getworldstories'


  post '/getstories', to: 'stories#getstories'
  post '/getstory', to: 'stories#getstory'
  post '/getstory_note', to: 'story_notes#getstory_note'
  post '/getstorycharacters', to: 'story_characters#getstorycharacters'
  post '/getstorylocations', to: 'story_locations#getstorylocations'
  post '/getstory_notes', to: 'story_notes#getstory_notes'
  

  post '/getlocation', to: 'locations#getlocation'
  post '/getlocations', to: 'locations#getlocations'
  post '/getcharacter', to: 'characters#getcharacter'
  post '/getcharacters', to: 'characters#getcharacters'




  post '/worlds/new', to: 'worlds#create'
  post '/stories/new', to: 'stories#create'
  post '/characters/new', to: 'characters#create'
  post '/locations/new', to: 'locations#create'
  post '/story_notes/new', to: 'story_notes#create'
  post '/world_notes/new', to: 'world_notes#create'









  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/world.rb
class World < ApplicationRecord
  belongs_to :user
  has_many :world_notes
  has_many :characters
  has_many :locations
  has_many :stories
  has_many :images
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
    def getworlds
        user = User.find(params['user']['user']['id'])
        worlds = user.worlds
        render :json => worlds
    end

    def getworld
        world = World.find(world_params['id'])
        render :json => world
    end

    def show
        byebug
    end

    def create
        user_id = world_params['user_id']
        name = world_params['name']
        description = world_params['description']
        newWorld = World.create(name: name, description: description, user_id: user_id)
        img_urls = world_params['img_url'].split(', ')
        img_urls.each do |url|
            Image.create(url: url, world_id: newWorld.id)
        end
        render :json => newWorld
    end

    def edit 
    end

    def update
        # byebug
        world = World.find(world_params['currentWorld'])
        name = world_params['name']
        description = world_params['description']
        world.update(name: name, description: description)
        img_urls = world_params['img_url'].split(', ')
        img_urls.each do |url|
            Image.create(url: url, world_id: world.id)
        end
        world.save
        render :json => world
        
    end

    def destroy
        world = World.find(world_params['id'] )
        world.destroy
        render :json => {
            message: 'World Deleted'
        }
    end

    private

    def world_params
        params.require(:world).permit(:name, :description, :user_id, :img_url, :currentWorld, :id)
    end

end

app/views/worlds/_form.html.erb
<%= form_with(model: world, local: true) do |form| %>
  <% if world.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(world.errors.count, "error") %> prohibited this world from being saved:</h2>

      <ul>
      <% world.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class='field'>
  <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :default_story_id %>
    <%= form.number_field :default_story_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worlds/edit.html.erb
<h1>Editing World</h1>

<%= render 'form', world: @world %>

<%= link_to 'Show', @world %> |
<%= link_to 'Back', worlds_path %>

app/views/worlds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Worlds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th>Default story</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worlds.each do |world| %>
      <tr>
        <td><%= world.name %></td>
        <td><%= world.description %></td>
        <td><%= world.user_id %></td>
        <td><%= world.default_story_id %></td>
        <td><%= link_to 'Show', world %></td>
        <td><%= link_to 'Edit', edit_world_path(world) %></td>
        <td><%= link_to 'Destroy', world, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New World', new_world_path %>

app/views/worlds/new.html.erb
<h1>New World</h1>

<%= render 'form', world: @world %>

<%= link_to 'Back', worlds_path %>

app/views/worlds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @world.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @world.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @world.user_id %>
</p>

<p>
  <strong>Default story:</strong>
  <%= @world.default_story_id %>
</p>

<%= link_to 'Edit', edit_world_path(@world) %> |
<%= link_to 'Back', worlds_path %>